[package]
name = "synfone"
edition = "2018"
version = "0.1.0"
authors = ["Graham Northup <grissess@nexusg.org>"]

[[bin]]
name = "synfone"
doc = false


[dependencies]
byteorder = "1.1.0"
rand = "0.3"
cpal = "0.13"
unicode-xid = "0.1.0"
quick-xml = "0.22.0"
midly = "0.5.2"
